### PR TITLE
Added .gitignore file

### PR DESCRIPTION
**Pull request by cristiandan**
It's better to ignore all the node_modules dependencies so that is easier to change the branch when you go to the next chapter of the tutorial.

Please merge it to the other branches as well.

### CODE REVIEW

**Review by marktani — CHANGES_REQUESTED** [review]
Cool! I will have a look at this. How could we slip this one? :slightly_smiling_face:

**Comment by marktani** [comment]
By the way, have you seen https://github.com/learnrelay/pokedex/blob/master/CONTRIBUTING.md? I'll handle this one, but please refer to it for future PRs.

Thanks for the PR :tada:

**Comment by cristiandan** [comment]
Sorry, I didn't know there was a contributing guide.
I can change my PR as requested in the guide.

**Comment by marktani** [comment]
Would be great!

**Pull request closed without merging**
